language: java

before_install:
  # Work around missing crypto in openjdk7
  - |
    if [ "$TRAVIS_JDK_VERSION" == "openjdk7" ]; then
      sudo wget "https://bouncycastle.org/download/bcprov-jdk15on-159.jar" -O "${JAVA_HOME}/jre/lib/ext/bcprov-jdk15on-159.jar"
      sudo perl -pi.bak -e 's/^(security\.provider\.)([0-9]+)/$1.($2+1)/ge' /etc/java-7-openjdk/security/java.security
      echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" | sudo tee -a /etc/java-7-openjdk/security/java.security
    fi

script:
  - ./gradlew --version
  - ./gradlew clean
  - if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then ./gradlew check; fi
  - ./gradlew test

matrix:
  include:
# 7
    - env: JDK='OpenJDK 7'
      jdk: openjdk7
# 8
    - env: JDK='Oracle JDK 8'
      jdk: oraclejdk8
    - env: JDK='OpenJDK 8'
      jdk: openjdk8
# 9
    - env: JDK='Oracle JDK 9'
      jdk: oraclejdk9
    - env: JDK='OpenJDK 9'
      install: openjdk9
# 10
    - env: JDK='Oracle JDK 10'
      jdk: oraclejdk10
    - env: JDK='OpenJDK 10'
      jdk: openjdk10
# 11
    - env: JDK='Oracle JDK 11'
      jdk: oraclejdk11
    - env: JDK='OpenJDK 11'
      jdk: openjdk11
