language: java

script:
  - ./gradlew --version
  - ./gradlew clean
  - if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then ./gradlew check; fi
  - ./gradlew test

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
