package com.chargehound;

import com.chargehound.resources.Disputes;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Chargehound {
  private int defaultHTTPTimeout = 60;
  private String apiVersion = null;
  private String basepath = "/v1/";
  private String host = "api.chargehound.com";
  private String key;
  private String protocol = "https://";
  public Disputes Disputes;

  // Creates a new chargehound client with the specified api key and the default configuration.
  public Chargehound(String key) {
    this.key = key;
    this.Disputes = new Disputes(this);
  }

  public void setApiProtocol(String protocol) {
    this.protocol = protocol;
  }

  public void setApiHost(String host) {
    this.host = host;
  }

  public void setApiBasepath(String basepath) {
    this.basepath = basepath;
  }

  public String getApiBase() {
    return this.protocol + this.host + this.basepath;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public String getApiVersion() {
    return this.apiVersion;
  }

  public void setDefaultHTTPTimeout(int defaultHTTPTimeout) {
    this.defaultHTTPTimeout = defaultHTTPTimeout;
  }

  public int getHTTPTimeout() {
    return this.defaultHTTPTimeout;
  }

  public String getApiKey() {
    return this.key;
  }
}


