package com.chargehound;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ChargehoundTest {
  @Test public void testChargehoundConstructor() {
    Chargehound chargehound = new Chargehound("test_123");

    assertEquals("test_123", chargehound.getApiKey());
  }

  @Test public void testOverrideApiHost() {
    Chargehound chargehound = new Chargehound("test_123");

    chargehound.setApiProtocol("http://");
    chargehound.setApiHost("test.test.com");

    assertEquals("http://test.test.com/v1/", chargehound.getApiBase());
  }

  @Test public void testDisputesResource() {
    Chargehound chargehound = new Chargehound("test_123");

    assertEquals("dp_123", chargehound.Disputes.retrieve("dp_123"));
  }
}
