name: Dependency Review

on:
  push:
    branches: ['main']
    
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dependency-review:
    uses: chargehound/security-workflows-public/.github/workflows/dependency-review-gradle.yml@test-gradle-submission
    with:
      java-version: 8