name: CodeQL

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  codeql-java:
    uses: chargehound/security-workflows-public/.github/workflows/codeql-java.yml@main
    with:
      build-mode: 'manual'
      build-command: './gradlew build'
      java-version: '8'
